### PR TITLE
moves to debian stretch for php7 support natively in the container

### LINKED ISSUE #1: Build fails due to php version
from build log: https://hub.docker.com/r/z3cka/c9-php/builds/bn4jdv5mrufvde82pvzq96u/
```
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update

pecl/xdebug requires PHP (version >= 7.0.0), installed version is 5.6.33-0+deb8u1
No valid packages found
install failed

Removing intermediate container 2860b16bc58f

The command '/bin/sh -c pecl install xdebug' returned a non-zero code: 1
```

### PR DESCRIPTION
**Pull request by z3cka**
Resolves #1. I will wait to merge the PR until i know I can successfully build and use downstream in https://hub.docker.com/r/z3cka/c9-phpbrew-drupal/builds/

### CODE REVIEW

**Comment by z3cka** [comment]
this was a bad idea as it is difficult if not impossible to support php 5.6 on stretch due to openssl versions

**Comment by h3ct0rjs** [comment]
Hi, I was wondering why Do you choose debian, what happend if you choose ubuntu and inside it install the nvm, maybe this could work

**Comment by z3cka** [comment]
Hi @h3ct0rjs, that's a good idea. I may make another tag that uses Ubuntu instead. The end goal is to have access to php 5 and 7 in the same dev environment via phpbrew. I can achieve this via Debian Jessie, so that is my current solution for now.

**Comment by h3ct0rjs** [comment]
seems pretty cool to me, I've checked some of your DockerFiles if you want a little help :smiley:. 
I'll keep an eye on your repos. 

Best Regards, 
Hector F.

**Pull request closed without merging**
